#### Redis 配置
spring:
   redis:
      #### Redis 数据库索引（默认为0）
      database: 1
      host: 101.226.249.33
      port: 6379
      password: 1qaz2wsxAAA
      jedis:
         pool:
            ### 连接池最大连接数（使用负值表示没有限制）
            max-active: 3
            ### 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
            ### 连接池最大空闲连接
            max-idle: 2
            ### 连接池最小空闲连接
            min-idle: 0
      ### 连接超时时间（毫秒）
      timeout: 10000
      
ms:
   ds:
      xas:
         minPoolSize: 3  
         maxPoolSize: 25  
         maxLifetime: 20000  
         borrowConnectionTimeout: 30  
         loginTimeout: 30  
         maintenanceInterval: 60  
         maxIdleTime: 60
         testQuery: select 1 
      source:
         - driver-class-name: com.mysql.jdbc.Driver
           url: jdbc:mysql://101.226.249.33:63306/mprocess?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
           username: root
           password:
           db-type: mysql
           key: default
         - driver-class-name: com.mysql.jdbc.Driver
           url: jdbc:mysql://101.226.249.33:63306/hxtest?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
           username: root
           password:
           db-type: mysql
           key: hxtest
         - driver-class-name: net.sourceforge.jtds.jdbc.Driver
           url: jdbc:jtds:sqlserver://101.226.249.32:1433;DatabaseName=CS6304
           username: mis
           password: Cdef200902
           db-type: jtds
           key: cs6304
         - driver-class-name: net.sourceforge.jtds.jdbc.Driver
           url: jdbc:jtds:sqlserver://101.226.249.32:1433;DatabaseName=NC6302
           username: mis
           password: Cdef200902
           db-type: jtds
           key: nc6302
         - driver-class-name: net.sourceforge.jtds.jdbc.Driver
           url: jdbc:jtds:sqlserver://101.226.249.46:1433;DatabaseName=amsflow
           username: sa
           password: e9wkYRHE
           db-type: jtds
           key: amsflow
         
      druid:
         # druid 部分
         #type: com.alibaba.druid.pool.DruidDataSource
         type: com.alibaba.druid.pool.xa.DruidXADataSource
         initialSize: 5   
         minIdle: 5   
         maxActive: 20
         maxWait: 60000
         timeBetweenEvictionRunsMillis: 600000
         minEvictableIdleTimeMillis: 300000
         validationQuery: SELECT 1 
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         poolPreparedStatements: true
         maxPoolPreparedStatementPerConnectionSize: 20
         filters: stat,wall,log4j
         connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
         logSlowSql: true
          
---
#entity扫描的包名
#Mapper.xml所在的位置
mybatis:
   type-aliases-package: com.ms.*,com.my.*,com.ams.*
   mapper-locations: classpath*:/mapper/**/*Mapper.xml
   #开启MyBatis的二级缓存
   configuration:
      cache-enabled: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




      